package error

const (
	SUCCESS        = 200
	ERROR          = 500
	INVALID_PARAMS = 400

	ERROR_EXIST_TAG         = 10001
	ERROR_NOT_EXIST_TAG     = 10002
	ERROR_NOT_EXIST_ARTICLE = 10003

	ERROR_AUTH_CHECK_TOKEN_FAIL     = 20001
	ERROR_AUTH_CHECK_TOKEN_TIMEOUT  = 20002
	ERROR_AUTH_TOKEN                = 20003
	ERROR_AUTH                      = 20004
	ERROR_ADMIN_NOT_EXIST           = 20005
	ERROR_NOT_SAME_ADMIN            = 20006
	ERROR_NOT_SEARCH                = 401
	ERROT_EXIST_USER_DISPLAY        = 402
	ERROR_NOT_PHONE                 = 403
	ERROR_NOT_EMAIL                 = 405
	ERROR_ADD_CONTENT_SUCCESS       = 406
	ERROR_ADD_CONTENT_ERROR         = 407
	ERROR_DELETE_CONTENT_NOT_MYSELF = 408
	ERROR_USER_NOT_EXIST            = 409
	ERROR_USER_NOT_ADMIN            = 410
	ERROR_FAVORITE_EXIST            = 411
	ERROR_USER_LOGIN                = 412
	ERROR_TAG_IS_QUOTE              = 413
	ERROR_VIDEO_DELETE_ERROE        = 414
)

const (
	ERROR_USER_EXIST = 300
)
